### ISSUE TITLE
Do not use FloodAdapt folder structure

### ISSUE THREAD

**Issue by panosatha** [Deltares/fiat_toolbox#11]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

It seems that while the InfographicsParser class is in fiat_toolbox, it is really tailored to the floodadapt database structure. Wouldn't it make more sense to not rely on this structure since this can be used outside of floodadapt as well?

### Current behaviour

Infographic can only be created under floodadapt structure

### Desired behaviour

Infographic should be created in any fiat model run outside of floodadapt

### Task list

- [ ] change infographic methods, so they explicitly read a config file instead of assumming it exists in a floodadapt structure
