### ISSUE TITLE
Enhance performance of the infometrics calculation

### ISSUE THREAD

**Issue by dladrichem** [Deltares/fiat_toolbox#20]
### Kind of request

Adding new functionality

### Enhancement Description

The informetrics calculation can take quite a lot of time. This needs to be faster

### Task list

- [ ] Test what parts take long
- [ ] Make it faster
- [ ] If needed, write unit tests
