### ISSUE TITLE
Infographic should contain relative path's

### ISSUE THREAD

**Issue by dladrichem** [Deltares/fiat_toolbox#42]
### Kind of request

Changing existing functionality

### Enhancement Description

Icons in the infographic have absolute paths to the static images in the database. If you then copy the database and send it to someone, created inforgraphics won't show up since the absolute path (the path to the database) changed. This should be fixed if you use relative path's (if possible). The save infographic option aready covers sending just the infographic to someone without the entire database.

### Task list

- [x] Check whether this is possible
- [x] Implement
- [x] Test that it still works
- [x] Test that if you change the name of the database, whether it still works (this should only change the absolute path)

### Use case

When you send the database to someone so the other person can use your pre-run scenario's
